<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20141011013611 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE famelo_saas_domain_model_inviterequest (persistence_object_identifier VARCHAR(40) NOT NULL, email VARCHAR(255) DEFAULT NULL, status VARCHAR(255) NOT NULL, createdat DATETIME NOT NULL, PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("ALTER TABLE famelo_saas_domain_model_inviterequest ADD CONSTRAINT FK_C4E4349747A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES famelo_soul_domain_model_soul (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("DROP TABLE famelo_saas_domain_model_inviterequestfragment");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE famelo_saas_domain_model_inviterequestfragment (persistence_object_identifier VARCHAR(40) NOT NULL, email VARCHAR(255) DEFAULT NULL, status VARCHAR(255) NOT NULL, createdat DATETIME NOT NULL, invitetoken VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("ALTER TABLE famelo_saas_domain_model_inviterequestfragment ADD CONSTRAINT FK_23843ECA47A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES famelo_soul_domain_model_abstractfragment (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("DROP TABLE famelo_saas_domain_model_inviterequest");
	}
}