<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140217225338 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE famelo_saas_domain_model_user DROP FOREIGN KEY FK_852E1B9FDD5A5B7D");
		$this->addSql("CREATE TABLE famelo_saas_domain_model_subscription (persistence_object_identifier VARCHAR(40) NOT NULL, team VARCHAR(40) DEFAULT NULL, created DATETIME NOT NULL, active TINYINT(1) NOT NULL, plan VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_585AAE69C4E0A61F (team), PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("CREATE TABLE famelo_saas_domain_model_team (persistence_object_identifier VARCHAR(40) NOT NULL, subscription VARCHAR(40) DEFAULT NULL, name VARCHAR(255) NOT NULL, active TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_CC5D6BC9A3C664D3 (subscription), PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("ALTER TABLE famelo_saas_domain_model_subscription ADD CONSTRAINT FK_585AAE69C4E0A61F FOREIGN KEY (team) REFERENCES famelo_saas_domain_model_team (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_saas_domain_model_team ADD CONSTRAINT FK_CC5D6BC9A3C664D3 FOREIGN KEY (subscription) REFERENCES famelo_saas_domain_model_subscription (persistence_object_identifier)");
		$this->addSql("DROP TABLE famelo_saas_domain_model_plan");
		$this->addSql("DROP INDEX IDX_852E1B9FDD5A5B7D ON famelo_saas_domain_model_user");
		$this->addSql("ALTER TABLE famelo_saas_domain_model_user CHANGE plan team VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE famelo_saas_domain_model_user ADD CONSTRAINT FK_852E1B9FC4E0A61F FOREIGN KEY (team) REFERENCES famelo_saas_domain_model_team (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_852E1B9FC4E0A61F ON famelo_saas_domain_model_user (team)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE famelo_saas_domain_model_team DROP FOREIGN KEY FK_CC5D6BC9A3C664D3");
		$this->addSql("ALTER TABLE famelo_saas_domain_model_subscription DROP FOREIGN KEY FK_585AAE69C4E0A61F");
		$this->addSql("ALTER TABLE famelo_saas_domain_model_user DROP FOREIGN KEY FK_852E1B9FC4E0A61F");
		$this->addSql("CREATE TABLE famelo_saas_domain_model_plan (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, cycle VARCHAR(255) NOT NULL, price DOUBLE PRECISION NOT NULL, PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("DROP TABLE famelo_saas_domain_model_subscription");
		$this->addSql("DROP TABLE famelo_saas_domain_model_team");
		$this->addSql("DROP INDEX IDX_852E1B9FC4E0A61F ON famelo_saas_domain_model_user");
		$this->addSql("ALTER TABLE famelo_saas_domain_model_user CHANGE team plan VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE famelo_saas_domain_model_user ADD CONSTRAINT FK_852E1B9FDD5A5B7D FOREIGN KEY (plan) REFERENCES famelo_saas_domain_model_plan (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_852E1B9FDD5A5B7D ON famelo_saas_domain_model_user (plan)");
	}
}