<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140225154125 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE famelo_saas_domain_model_transaction (persistence_object_identifier VARCHAR(40) NOT NULL, subscription VARCHAR(40) DEFAULT NULL, created DATETIME NOT NULL, amount DOUBLE PRECISION NOT NULL, note VARCHAR(255) NOT NULL, INDEX IDX_3AB1DA8EA3C664D3 (subscription), PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("ALTER TABLE famelo_saas_domain_model_transaction ADD CONSTRAINT FK_3AB1DA8EA3C664D3 FOREIGN KEY (subscription) REFERENCES famelo_saas_domain_model_subscription (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_saas_domain_model_subscription ADD balance DOUBLE PRECISION NOT NULL");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("DROP TABLE famelo_saas_domain_model_transaction");
		$this->addSql("ALTER TABLE famelo_saas_domain_model_subscription DROP balance");
	}
}