<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140803164750 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_saas_domain_model_transaction ADD tenant VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE famelo_saas_domain_model_transaction ADD CONSTRAINT FK_3AB1DA8E4E59C462 FOREIGN KEY (tenant) REFERENCES famelo_harvest_domain_model_user (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_3AB1DA8E4E59C462 ON famelo_saas_domain_model_transaction (tenant)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_saas_domain_model_transaction DROP FOREIGN KEY FK_3AB1DA8E4E59C462");
		$this->addSql("DROP INDEX IDX_3AB1DA8E4E59C462 ON famelo_saas_domain_model_transaction");
		$this->addSql("ALTER TABLE famelo_saas_domain_model_transaction DROP tenant");
	}
}