<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20141009221456 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE famelo_saas_domain_model_billing (persistence_object_identifier VARCHAR(40) NOT NULL, plan VARCHAR(40) DEFAULT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, company VARCHAR(255) NOT NULL, address VARCHAR(255) NOT NULL, address2 VARCHAR(255) NOT NULL, city VARCHAR(255) NOT NULL, state VARCHAR(255) NOT NULL, zip VARCHAR(255) NOT NULL, country VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(255) NOT NULL, fax VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_AEA26312DD5A5B7D (plan), PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("CREATE TABLE famelo_saas_domain_model_inviterequest (persistence_object_identifier VARCHAR(40) NOT NULL, email VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, createdat DATETIME NOT NULL, number INT NOT NULL, invitetoken VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("CREATE TABLE famelo_saas_domain_model_plan (persistence_object_identifier VARCHAR(40) NOT NULL, billing VARCHAR(40) DEFAULT NULL, created DATETIME NOT NULL, active TINYINT(1) NOT NULL, type VARCHAR(255) NOT NULL, balance DOUBLE PRECISION NOT NULL, currency VARCHAR(255) NOT NULL, cycle VARCHAR(255) NOT NULL, cyclestart DATETIME NOT NULL, cyclenext DATETIME NOT NULL, cyclecost DOUBLE PRECISION NOT NULL, UNIQUE INDEX UNIQ_D5E796ABEC224CAA (billing), PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("CREATE TABLE famelo_saas_domain_model_transaction (persistence_object_identifier VARCHAR(40) NOT NULL, plan VARCHAR(40) DEFAULT NULL, tenant VARCHAR(40) DEFAULT NULL, created DATETIME NOT NULL, amount DOUBLE PRECISION NOT NULL, currency VARCHAR(255) NOT NULL, note VARCHAR(255) DEFAULT NULL, paymentgateway VARCHAR(255) DEFAULT NULL, invoicenumber VARCHAR(255) DEFAULT NULL, state VARCHAR(255) NOT NULL, INDEX IDX_3AB1DA8EDD5A5B7D (plan), INDEX IDX_3AB1DA8E4E59C462 (tenant), PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("ALTER TABLE famelo_saas_domain_model_billing ADD CONSTRAINT FK_AEA26312DD5A5B7D FOREIGN KEY (plan) REFERENCES famelo_saas_domain_model_plan (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_saas_domain_model_plan ADD CONSTRAINT FK_D5E796ABEC224CAA FOREIGN KEY (billing) REFERENCES famelo_saas_domain_model_billing (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_saas_domain_model_transaction ADD CONSTRAINT FK_3AB1DA8EDD5A5B7D FOREIGN KEY (plan) REFERENCES famelo_saas_domain_model_plan (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_saas_domain_model_transaction ADD CONSTRAINT FK_3AB1DA8E4E59C462 FOREIGN KEY (tenant) REFERENCES typo3_party_domain_model_abstractparty (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE famelo_saas_domain_model_plan DROP FOREIGN KEY FK_D5E796ABEC224CAA");
		$this->addSql("ALTER TABLE famelo_saas_domain_model_billing DROP FOREIGN KEY FK_AEA26312DD5A5B7D");
		$this->addSql("ALTER TABLE famelo_saas_domain_model_transaction DROP FOREIGN KEY FK_3AB1DA8EDD5A5B7D");
		$this->addSql("DROP TABLE famelo_saas_domain_model_billing");
		$this->addSql("DROP TABLE famelo_saas_domain_model_inviterequest");
		$this->addSql("DROP TABLE famelo_saas_domain_model_plan");
		$this->addSql("DROP TABLE famelo_saas_domain_model_transaction");
	}
}