<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140805002418 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_harvest_domain_model_user ADD template VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE famelo_harvest_domain_model_user ADD CONSTRAINT FK_B5967D4B97601F83 FOREIGN KEY (template) REFERENCES famelo_harvest_domain_model_template (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_B5967D4B97601F83 ON famelo_harvest_domain_model_user (template)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_harvest_domain_model_user DROP FOREIGN KEY FK_B5967D4B97601F83");
		$this->addSql("DROP INDEX IDX_B5967D4B97601F83 ON famelo_harvest_domain_model_user");
		$this->addSql("ALTER TABLE famelo_harvest_domain_model_user DROP template");
	}
}