<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140130234517 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE famelo_saas_domain_model_plan (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, cycle VARCHAR(255) NOT NULL, price DOUBLE PRECISION NOT NULL, PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("CREATE TABLE famelo_saas_domain_model_user (persistence_object_identifier VARCHAR(40) NOT NULL, plan VARCHAR(40) DEFAULT NULL, phone VARCHAR(255) NOT NULL, mobile VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, INDEX IDX_852E1B9FDD5A5B7D (plan), PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("ALTER TABLE famelo_saas_domain_model_user ADD CONSTRAINT FK_852E1B9FDD5A5B7D FOREIGN KEY (plan) REFERENCES famelo_saas_domain_model_plan (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_saas_domain_model_user ADD CONSTRAINT FK_852E1B9F47A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES typo3_party_domain_model_abstractparty (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("DROP TABLE famelo_saas_domain_model_person");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE famelo_saas_domain_model_user DROP FOREIGN KEY FK_852E1B9FDD5A5B7D");
		$this->addSql("CREATE TABLE famelo_saas_domain_model_person (persistence_object_identifier VARCHAR(40) NOT NULL, phone VARCHAR(255) NOT NULL, mobile VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("ALTER TABLE famelo_saas_domain_model_person ADD CONSTRAINT FK_66B055F47A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES typo3_party_domain_model_abstractparty (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("DROP TABLE famelo_saas_domain_model_plan");
		$this->addSql("DROP TABLE famelo_saas_domain_model_user");
	}
}