-
  name: 'Logout'
  uriPattern: 'logout.html'
  defaults:
    '@format': 'html'
    '@controller': 'Login'
    '@action':     'logout'
    '@package': 'Famelo.Saas'

-
  name: 'Invoice'
  uriPattern: 'invoice'
  defaults:
    '@format': 'html'
    '@controller': 'Invoice'
    '@action':     'index'
    '@package': 'Famelo.Saas'
  appendExceedingArguments: true