Famelo:
  Saas:
    adminEmail: mneuhaus@famelo.com

    defaults:
      InvoiceDocument: "Famelo.Saas:Invoice"
      InvoiceMessage: "Famelo.Saas:Invoice"
      plan: 'Deposit'
      currency: 'EUR'
      balance: 5

#    Plans: []
      # Free:
      #   name: "Free"
      #   cycle: "1 month"
      #   implementation: "Famelo\\Saas\\Plan\\FlatrateImplementation"
      #   choosable: true
      #   amount: 0.0

      # Small:
      #   name: "Small"
      #   cycle: "1 month"
      #   implementation: "Famelo\\Saas\\Plan\\FlatrateImplementation"
      #   choosable: true
      #   amount: 5.0

      # Large:
      #   name: "Large"
      #   cycle: "1 month"
      #   implementation: "Famelo\\Saas\\Plan\\FlatrateImplementation"
      #   choosable: true
      #   amount: 10.0

      # Deposit:
      #   name: "Deposit"
      #   cycle: "1 month"
      #   implementation: "Famelo\\Saas\\Plan\\DepositImplementation"
      #   choosable: true
      #   amount: 10.0

      # Billing:
      #   name: "Billing"
      #   cycle: "1 month"
      #   implementation: "Famelo\\Saas\\Plan\\DepositImplementation"
      #   choosable: true
      #   amount: 10.0

    PaymentGateways:
      Invoice:
          name: "Invoice"
          gateway: Manual
      PayPal:
          name: "PayPal Express"
          gateway: PayPal_Express
          parameters:
            username: sandbox-facilitator_api1.famelo.com
            password: 1393410139
            signature: AfeGGKOlXPvusrtcaK4I8f8TUGQUAg7eNYweX2MSkTIspTix6sWzHHqm
            testMode: true
            brandName: 'Broensfin'

    usePoints: true
    exchangeRates:
      EUR: 0.5
      USD: 0.2
    taxes:
      DE:
        name: "MwSt."
        amount: 19
        type: included
        labels:
          subtotal: "Zwischensumme (netto)"
          tax: "zzgl. MwSt. 19,00%"
          total: "Gesamtsumme (brutto)"

TYPO3:
  Flow:
    object:
      excludeClasses:
       'Omnipay.Common': ['.*']