TYPO3:
  Flow:
    security:
      authentication:
        providers:
          SaasProvider:
            provider: PersistedUsernamePasswordProvider
            entryPoint: 'WebRedirect'
            entryPointOptions:
              uri: login
            requestPatterns:
              controllerObjectName: 'Famelo\Saas\Controller\.*'
    i18n:
      # The default locale identifier.
      defaultLocale: de

  Neos:
    typoScript:
      autoInclude:
        'Famelo.Saas': TRUE